# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dual_finger_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64ual_finger_msg.proto\x12\nDualFinger\"\x9f\x01\n\nDualFinger\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\r\n\x05img_0\x18\x02 \x01(\x0c\x12\x0e\n\x06pose_0\x18\x03 \x03(\x01\x12\x0f\n\x07\x66orce_0\x18\x04 \x03(\x01\x12\x0e\n\x06node_0\x18\x05 \x03(\x01\x12\r\n\x05img_1\x18\x06 \x01(\x0c\x12\x0e\n\x06pose_1\x18\x07 \x03(\x01\x12\x0f\n\x07\x66orce_1\x18\x08 \x03(\x01\x12\x0e\n\x06node_1\x18\t \x03(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dual_finger_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUALFINGER._serialized_start=38
  _DUALFINGER._serialized_end=197
# @@protoc_insertion_point(module_scope)
