# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frobot_msg.proto\x12\x05Robot\"\xcb\x01\n\x05Robot\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\r\n\x05img_1\x18\x02 \x01(\x0c\x12\x0e\n\x06pose_1\x18\x03 \x03(\x01\x12\x0f\n\x07\x66orce_1\x18\x04 \x03(\x01\x12\x0e\n\x06node_1\x18\x05 \x03(\x01\x12\r\n\x05img_2\x18\x06 \x01(\x0c\x12\x0e\n\x06pose_2\x18\x07 \x03(\x01\x12\x0f\n\x07\x66orce_2\x18\x08 \x03(\x01\x12\x0e\n\x06node_2\x18\t \x03(\x01\x12\x14\n\x0cjoint_angles\x18\n \x03(\x01\x12\x0c\n\x04pose\x18\x0b \x03(\x01\x12\x0b\n\x03img\x18\x0c \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROBOT._serialized_start=27
  _ROBOT._serialized_end=230
# @@protoc_insertion_point(module_scope)
