# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frobot_msg.proto\x12\x05Robot\"K\n\x05Robot\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x14\n\x0cjoint_angles\x18\x02 \x03(\x01\x12\x0c\n\x04pose\x18\x03 \x03(\x01\x12\x0b\n\x03img\x18\x04 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROBOT._serialized_start=26
  _ROBOT._serialized_end=101
# @@protoc_insertion_point(module_scope)
